name: Install Node
description: Checkout et installation de node
inputs: 
  node-version: 
    type: string
    required: true
    
runs: 
  using: 'composite'
  steps: 
    - name: Checkout main branch
      uses: actions/checkout@v4
      
    - name: Install NodeJs
      uses: actions/setup-node@v4
      with: 
        node-version: ${{inputs.node-version}}
