name: Install Node
on: 
  workflow_call:
    inputs: 
      node-version: 
        type: string
        required: true

jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout main branch
      uses: actions/checkout@v4
      
    - name: Install NodeJs
      uses: actions/setup-node@v4
      with: 
        node-version: ${{inputs.node-version}}
