name: Create Release
on: 
  workflow_dispatch: 
    inputs:
      type:
        description: 'NPM Version type'
        required: true
        default: 'patch'
        type: choice
        options:
        - patch
        - minor
        - major

jobs: 
  release: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16.x

      - name: NPM version
        env:
          EMAIL: llona.andre26@gmail.com
          NAME: Akalysna
        run: | 
          git config user.email $EMAIL
          git config user.name $NAME
          npm version ${{ inputs.type }}
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
          delete-branch: true

      - name: Get package version
        id: get_version
        run: echo ::set-output name=VERSION::$(node -e "console.log(require('./package.json').version)")

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          release_name: Release ${{ steps.get_version.outputs.VERSION }}
          body: Release ${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false
