name: Create Tag
on: 
  workflow_dispatch: 
    inputs:
      type:
        description: 'NPM Version type'
        required: true
        default: 'patch'
        type: choice
        options:
        - patch
        - minor
        - major

jobs: 
  create-tag: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: NPM version
        run: | 
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          npm version ${{ inputs.type }}
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
          delete-branch: true
